version: '3.8'
services:
    odoo:
        build: .
        depends_on:
          - db
        container_name: odoo
        command: sleep infinity
        ports:
            - 8069:8069
        networks:
          - odoo_network
        volumes:
          - ./repos/seguros/addons/extra-addons/seguros:/mnt/extra-addons/seguros
          - ./repos/global/addons/custom-addons:/mnt/extra-addons/custom-addons
          - ./repos/global/addons/enterprise-16.0:/mnt/extra-addons/enterprise
          - ./repos/global/addons/third_addons:/mnt/extra-addons/third_addons

    db:
      image: postgres:15.4
      container_name: postgresql
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD=odoo
        - POSTGRES_USER=odoo
      ports:
        - 5432:5432
      networks:
        - odoo_network
networks:
  odoo_network:
    driver: bridge
