version: '3.8'
services:
    odoo:
        build: .
        depends_on:
          - db
        container_name: odoo
        command: sleep infinity
        ports:
            - 8069:8069
        networks:
          - odoo_network
        environment:
          - ODOO_UPDATE_MODULES="insurance_mediators"
        volumes:
          - odoo-web-data:/var/lib/odoo/odoo-data
    db:
      image: postgres:15.4
      container_name: postgresql
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD=odoo
        - POSTGRES_USER=odoo
        - PGDATA=/var/lib/postgresql/data/dbfiles
      volumes:
        - odoo-db-data:/var/lib/postgresql/data/dbfiles
      ports:
        - 5432:5432
      networks:
        - odoo_network
volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo_network:
    driver: bridge
